"""dierci3

Revision ID: 17ece265e858
Revises: ba4594e0e79a
Create Date: 2018-05-23 23:06:23.132011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ece265e858'
down_revision = 'ba4594e0e79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fk_yanzheng',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_data', sa.String(length=100), nullable=False),
    sa.Column('info', sa.String(length=1000), nullable=False),
    sa.Column('open_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fk_yanzheng')
    # ### end Alembic commands ###
