"""dierci5

Revision ID: f16997e6eb80
Revises: 598754c09616
Create Date: 2018-05-23 23:42:42.979681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16997e6eb80'
down_revision = '598754c09616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fk_invitation', sa.Column('info_data', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fk_invitation', 'info_data')
    # ### end Alembic commands ###
